version: "3.8"
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80/tcp"
    db:
        container_name: pg_spotifyMe
        image: postgres:13.2-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: spotify
            POSTGRES_HOST_AUTH_METHOD: trust
            PGUSER: postgres
        ports:
            - "5432:5432"
    pgadmin:
        container_name: pgadmin_spotifyMe
        image: dpage/pgadmin4:5.2
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ericdwkim.io@gmail.com
            PGADMIN_DEFAULT_PASSWORD: ${pgadmin_password}
            PGADMIN_LISTEN_PORT: 5433
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
            PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
        ports:
            - "5433:5433"
        depends_on:
            - pg
networks:
    default:
        name: nunet
