version: "3.8"
services:
    db:
        container_name: pg_spotifyMe
        image: ericdwkim/spotify-me-pg:v1
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: spotify
            POSTGRES_HOST_AUTH_METHOD: trust
            PGUSER: postgres
        ports:
            - "5432:5432"
        # volumes:
        #     -postgresdata:/var/lib/postgresql/data:ro
        networks:
            - app-network
    app:
        container_name: app_spotifyMe
        image: ericdwkim/spotifyme-flask:v1
        depends_on:
          - db
        build: .
        restart: always
        ports:
            - "5000:5000"
        environment:
            FLASK_ENV: development
        # volumes:
        #     -hostPath:containerPath:ro
        networks:
            - app-network
    pgadmin:
        container_name: pgadmin_spotifyMe
        image: ericdwkim/spotify-me-pgadmin:v1
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ericdwkim.io@gmail.com
            PGADMIN_DEFAULT_PASSWORD: ${pgadmin_password}
            PGADMIN_LISTEN_PORT: 5433
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
            PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
        ports:
            - "5433:5433"
        depends_on:
            - db
        networks:
            - app-network
volumes:
    postgresdata:
networks:
    app-network:
        driver: bridge

