version: "3.8"
services:
    app:
        container_name: app_spotifyMe
        image: ericdwkim/spotifyme-flask:v2
        depends_on:
          - db
        build: .
        restart: always
        ports:
            - "5000"
        environment:
            FLASK_ENV: development
            FLASK_APP: __init__.py
        volumes:
            - postgresdata:/var/lib/postgresql/data
        networks:
            - app-network
            
    db:
        container_name: pg_spotifyMe
        image: ericdwkim/spotify-me-pg:v1
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: spotify
            POSTGRES_PASSWORD: admin123
            PGDATA: /var/lib/postgresql/data            
        ports:
            - "5432:5432"
        volumes:
            - postgresdata:/var/lib/postgresql/data
            # -
            #     type: bind
            #     source: /tmp/postgres-data
            #     target: /var/lib/postgresql/data
        networks:
            - app-network
            
    pgadmin:
        container_name: pgadmin_spotifyMe
        image: ericdwkim/spotify-me-pgadmin:v1
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ericdwkim.io@gmail.com
            PGADMIN_DEFAULT_PASSWORD: admin123
            PGADMIN_LISTEN_PORT: 5433
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
            PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
        ports:
            - "5433:5433"
        depends_on:
            - db
        volumes:
            - ./data/pgadmin:/var/lib/pgadmin
        networks:
            - app-network
networks:
    app-network:
        driver: bridge

volumes:
    postgresdata:
