"""empty message

Revision ID: 081420648416
Revises: 9dd10f281670
Create Date: 2021-11-23 21:10:30.605049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081420648416'
down_revision = '9dd10f281670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio',
    sa.Column('audio_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audio_URI', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('audio_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio')
    # ### end Alembic commands ###
