"""empty message

Revision ID: 227279671062
Revises: e30837abdb93
Create Date: 2021-11-20 11:35:14.647754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227279671062'
down_revision = 'e30837abdb93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_artists',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('account_id', 'artist_id')
    )
    op.create_table('groups_artists',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('group_id', 'artist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups_artists')
    op.drop_table('accounts_artists')
    # ### end Alembic commands ###
