"""empty message

Revision ID: 2ac1334b2966
Revises: 572da3397895
Create Date: 2021-12-13 11:43:27.060295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac1334b2966'
down_revision = '572da3397895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_num_members', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'group_num_members')
    # ### end Alembic commands ###
