"""empty message

Revision ID: 7b8ee561934a
Revises: 
Create Date: 2021-11-17 08:40:40.824824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8ee561934a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('albums',
    sa.Column('album_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('album_title', sa.String(length=128), nullable=False),
    sa.Column('album_length', sa.Integer(), nullable=False),
    sa.Column('artwork_url', sa.String(length=280), nullable=False),
    sa.Column('num_of_songs', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('album_id')
    )
    op.create_table('artists',
    sa.Column('artist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artist_name', sa.String(length=128), nullable=False),
    sa.Column('artist_bio', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('songs',
    sa.Column('song_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('song_title', sa.String(length=128), nullable=False),
    sa.Column('song_writer', sa.String(length=128), nullable=False),
    sa.Column('song_producer', sa.String(length=128), nullable=False),
    sa.Column('song_length', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('song_id')
    )
    op.create_table('songs_artists',
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs_artists')
    op.drop_table('songs')
    op.drop_table('groups')
    op.drop_table('artists')
    op.drop_table('albums')
    op.drop_table('accounts')
    # ### end Alembic commands ###
