"""empty message

Revision ID: 845a6c63851c
Revises: 628064e1f23d
Create Date: 2021-11-24 12:54:56.590485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845a6c63851c'
down_revision = '628064e1f23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audios',
    sa.Column('audio_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audio_url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('audio_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audios')
    # ### end Alembic commands ###
