"""empty message

Revision ID: 9dd10f281670
Revises: 227279671062
Create Date: 2021-11-20 16:37:42.012041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd10f281670'
down_revision = '227279671062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_artists',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('account_id', 'artist_id')
    )
    op.create_table('albums_artists',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('album_id', 'artist_id')
    )
    op.create_table('groups_artists',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('group_id', 'artist_id')
    )
    op.create_table('songs_albums',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], ),
    sa.PrimaryKeyConstraint('song_id', 'album_id')
    )
    op.alter_column('songs_artists', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('songs_artists', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs_artists', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('songs_artists', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('songs_albums')
    op.drop_table('groups_artists')
    op.drop_table('albums_artists')
    op.drop_table('accounts_artists')
    # ### end Alembic commands ###
