"""empty message

Revision ID: e30837abdb93
Revises: 0878515982d5
Create Date: 2021-11-19 20:49:37.512466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30837abdb93'
down_revision = '0878515982d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs_albums',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], ),
    sa.PrimaryKeyConstraint('song_id', 'album_id')
    )
    op.drop_table('groups_artists')
    op.drop_constraint('accounts_artist_id_key', 'accounts', type_='unique')
    op.drop_constraint('fk_accounts_artists', 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'artist_id')
    op.drop_constraint('songs_album_id_key', 'songs', type_='unique')
    op.drop_constraint('fk_songs_albums', 'songs', type_='foreignkey')
    op.drop_column('songs', 'album_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('album_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_songs_albums', 'songs', 'albums', ['album_id'], ['album_id'])
    op.create_unique_constraint('songs_album_id_key', 'songs', ['album_id'])
    op.add_column('accounts', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_accounts_artists', 'accounts', 'artists', ['artist_id'], ['artist_id'])
    op.create_unique_constraint('accounts_artist_id_key', 'accounts', ['artist_id'])
    op.create_table('groups_artists',
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], name='fk_groups_artists_artists'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], name='fk_groups_artists_groups'),
    sa.PrimaryKeyConstraint('group_id', 'artist_id', name='groups_artists_pkey')
    )
    op.drop_table('songs_albums')
    # ### end Alembic commands ###
